# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2beeabfb0169d4cb459b4434f2da18ae394db41e9ca966bb4d2b62e025f64b6927db5efd3ae7c6a0cb1845cd0e221b9843cd97875d5104353401c68c3b02f03

test:
  secret_key_base: 07b8c1576e65c309bb3c2ecefa290b78151ec5f58f82169290f70f58705813c46decadb333be1b1db47f1d69e1e666ad0e9ab4acdabfb2234cf5d2188a05b077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
