Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'super_hot', season: 'any', phrase: 'Triple digits, WTF?!')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'super_hot', season: 'any', phrase: 'Yah. It\'s a dry heat.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'super_hot', season: 'any', phrase: 'Just throw some water at me.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'super_hot', season: 'any', phrase: 'Water..... waterrrrr.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'super_hot', season: 'any', phrase: 'It\'s a spontaneous combustion kind of day.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'super_hot', season: 'any', phrase: 'Have mercy, sun.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'super_hot', season: 'any', phrase: 'Tell the Heat Miser to fuck off.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'super_hot', season: 'any', phrase: 'Can I lay in your freezer for a while?')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'super_hot', season: 'any', phrase: 'Must... find... Bomb pop.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'hot', season: 'any', phrase: 'It\'s a dry heat.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'hot', season: 'any', phrase: 'Hot enough for ya?')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'hot', season: 'any', phrase: 'Is it winter yet?')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'hot', season: 'any', phrase: 'Time for a long walk off a short dock.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'hot', season: 'any', phrase: 'Go jump in a lake? Yes, please.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'hot', season: 'any', phrase: 'That damn weather, so hot right now.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'hot', season: 'any', phrase: 'So. Sweaty.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'hot', season: 'any', phrase: 'Did I put on deodorant? Oh well.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'hot', season: 'any', phrase: 'Too hot. I\'m going to Canada.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'hot', season: 'any', phrase: 'Perfect day to film a super soaker commercial.')
Phrase.create(stock_image_id: 3, temperature: 'hot', condition: 'humid', season: 'any', phrase: 'I\'m sticky.')
Phrase.create(stock_image_id: 3, temperature: 'hot', condition: 'humid', season: 'any', phrase: 'Must. Find. AC.')
Phrase.create(stock_image_id: 3, temperature: 'hot', condition: 'humid', season: 'any', phrase: 'So. Sweaty.')
Phrase.create(stock_image_id: 3, temperature: 'hot', condition: 'humid', season: 'any', phrase: 'Am I in Alabama?')
Phrase.create(stock_image_id: 3, temperature: 'hot', condition: 'humid', season: 'any', phrase: 'I\'m MELTTTTINNNGGG!')
Phrase.create(stock_image_id: 3, temperature: 'hot', condition: 'humid', season: 'any', phrase: 'It\'s a dry heat my ass.')
Phrase.create(stock_image_id: 3, temperature: 'hot', condition: 'humid', season: 'any', phrase: 'Get me a light beer, stat!')
Phrase.create(stock_image_id: 3, temperature: 'hot', condition: 'humid', season: 'any', phrase: 'It\'s like I\'m walking in a soup.')
Phrase.create(stock_image_id: 3, temperature: 'hot', condition: 'humid', season: 'any', phrase: 'Word of the day: stifling.')
Phrase.create(stock_image_id: 3, temperature: 'warm', condition: 'clear', season: 'any', phrase: 'Heck of a nice day')
Phrase.create(stock_image_id: 3, temperature: 'warm', condition: 'clear', season: 'any', phrase: 'One of the fourteen nice days a year')
Phrase.create(stock_image_id: 3, temperature: 'warm', condition: 'clear', season: 'any', phrase: 'Yah sure, you betcha!')
Phrase.create(stock_image_id: 3, temperature: 'warm', condition: 'clear', season: 'any', phrase: 'Geez. This isn\'t so bad.')
Phrase.create(stock_image_id: 3, temperature: 'warm', condition: 'clear', season: 'any', phrase: 'Put your phone down, go do something outside.')
Phrase.create(stock_image_id: 3, temperature: 'warm', condition: 'clear', season: 'any', phrase: 'Time for some ice cream.')
Phrase.create(stock_image_id: 3, temperature: 'warm', condition: 'clear', season: 'any', phrase: 'How about a beer?')
Phrase.create(stock_image_id: 3, temperature: 'warm', condition: 'clear', season: 'any', phrase: 'Time to work on my farmer\'s tan.')
Phrase.create(stock_image_id: 3, temperature: 'warm', condition: 'clear', season: 'any', phrase: 'Gotta redden up my neck.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'below_freezing', season: 'winter', phrase: 'Oh geez, it\'s shorts weather!')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'below_freezing', season: 'winter', phrase: 'Make a snowman!')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'below_freezing', season: 'winter', phrase: 'Download Sled finder and record a sledding route!')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'below_freezing', season: 'winter', phrase: 'Try a new winter sport. XC ski, snowshoeing, biking, ice fishing.')
Phrase.create(stock_image_id: 3, temperature: 'below_freezing', condition: 'windy', phrase: 'It\'s not the cold that get\'s ya... It\'s that wind!')
Phrase.create(stock_image_id: 3, temperature: 'below_freezing', condition: 'windy', phrase: 'Weatherman says there\'s a strong wind shield today.')
Phrase.create(stock_image_id: 3, temperature: 'below_freezing', condition: 'windy', phrase: 'Is it summer yet?')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'below_freezing', season: 'any', phrase: 'It\'s freezing.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'below_freezing', season: 'any', phrase: 'Hope you are a hockey fan.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'below_zero', season: 'any', phrase: 'Must be one of them polar vertexs.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'below_zero', season: 'any', phrase: 'Sven Sundgard. I blame YOU.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'below_zero', season: 'any', phrase: 'Don\'t forget a pair of choppers.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'below_zero', season: 'any', phrase: 'That\'s it, I\'m moving to [warm location]')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'below_zero', season: 'any', phrase: 'Just pretend you\'re dead to the world and go back to sleep.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'below_zero', season: 'any', phrase: 'Fuck it, let\'s go ice fishing..')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'way_below_zero', season: 'any', phrase: 'Fuck you, Canada.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'way_below_zero', season: 'any', phrase: 'Just don\'t bother.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'way_below_zero', season: 'any', phrase: 'Cold enough for ya?')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'way_below_zero', season: 'any', phrase: 'Dear God, make it stop.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'way_below_zero', season: 'any', phrase: 'Your skin may freeze in less than a minute. Consider it a challenge.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'way_below_zero', season: 'any', phrase: 'If you go outside, just try not to die.')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'way_below_zero', season: 'any', phrase: 'You know there are people in the world who don\'t have to put up with all of this shit?')
Phrase.create(stock_image_id: 3, condition: 'any', temperature: 'way_below_zero', season: 'any', phrase: 'Fuck it, I\'m moving to [warm location].')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'winter', phrase: 'Enjoy it before you have to shovel')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'winter', phrase: 'Better than rain, right?')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'winter', phrase: 'Yay, my favorite hobby, shoveling!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'winter', phrase: 'Woo hoo, I love raking my roof!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'spring', phrase: 'Fuck winter.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'spring', phrase: 'This had damn well better be the last.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'spring', phrase: 'Damn it.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'spring', phrase: 'No. Not acceptable. STOP IT!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'spring', phrase: 'NOOOOOOOOOOOOO!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'spring', phrase: 'You know there are people in the world who don\'t have to put up with all of this shit?')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'spring', phrase: 'Lousy Smarch weather.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'fall', phrase: 'Winter is coming.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'fall', phrase: 'NOOooooOOOOOO!!!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'snowy', season: 'fall', phrase: 'Does not compute.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'sleet', season: 'any', phrase: 'Everyone\'s favorite driving weather')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'sleet', season: 'any', phrase: 'Yay, sleet!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'sleet', season: 'any', phrase: 'Watch out for falling electrical poles.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'sleet', season: 'any', phrase: 'Live in [location], what was I thinking?')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'fog', season: 'any', phrase: 'What\'s this shit, San Francisco?')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'fog', season: 'any', phrase: 'Does not compute.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'fog', season: 'any', phrase: 'Everyone\'s second favorite driving weather!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'hail', season: 'any', phrase: 'Better check that insurance policy.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'hail', season: 'any', phrase: 'Yay, time for a new roof!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'hail', season: 'any', phrase: 'Ever hit golf ball sized hail with a golf club?')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'disaster', season: 'any', phrase: 'Hide yo kids, hide yo wife.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'disaster', season: 'any', phrase: 'Help!!!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'disaster', season: 'any', phrase: 'Oh shit, get inside!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'disaster', season: 'any', phrase: 'HELLLLLLLLLLLLLLLPPPPPPPP ME!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'disaster', season: 'any', phrase: 'Help me buddha, jesus, mohammad and jobu!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'disaster', season: 'any', phrase: 'Pick a religion and start praying.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'disaster', season: 'any', phrase: 'Time to earn that paycheck, national weather on site reporters.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'thunder', season: 'any', phrase: 'Thunder on the prarie.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'thunder', season: 'any', phrase: 'Fly a kite Ben Franklin.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'rain', season: 'any', phrase: 'What\'s on TV?')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'rain', season: 'any', phrase: 'Rain? Go away.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'rain', season: 'any', phrase: 'This weather is ASS.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'rain', season: 'any', phrase: 'Fuck this shit.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'rain', season: 'any', phrase: 'Mother nature, you\'re a chode.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'rain', season: 'any', phrase: 'God damnit.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'drizzle', season: 'any', phrase: 'The drizzle, fo shizzle.')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'clear', season: 'any', phrase: 'Aw HELL yeah!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'clear', season: 'any', phrase: 'Is this why people move to California?')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'clear', season: 'any', phrase: 'Live in [location], I\'m a genius!')
Phrase.create(stock_image_id: 3, temperature: 'any', condition: 'overcast', season: 'any', phrase: 'Go back to Seattle, clouds.')
